### ISSUE TITLE
Add allowfullscreen option

### ISSUE THREAD

**Issue by danielmiclos** [ryanseddon/react-frame-component#75] opened 2017-07-10 18:34 UTC
Hello, 

I'm working in a user interface that has a video player a some moments. So I'm using the iframe component to encapsulate it and be able to control the player size in a more fluid way. 

The only point is that, to be able to see the video in full screen, the iFrame must also have the allowfullscreen property or the video will only expand to the iframe constraints.
Is there a way to add the allowfullscreen property?

**Comment by ryanseddon** [comment] 2017-07-12 07:16
Great want to add a PR for this?

**Comment by ericnkatz** [comment] 2017-08-01 14:16
Doesn't this already work if you just apply the allowfullscreen props to the <Frame> component?

**Comment by s3thi** [comment] 2017-09-26 10:58
I can confirm that adding `allowfullscreen` to `<Frame>` works perfectly.

**Comment by ryanseddon** [comment] 2017-09-26 22:08
Now that react 16 is out these annoying issues will go away once I upgrade since it'll pass through all attributes without complaint. Closing since this seems to work already.

**Closed by ryanseddon** 2017-09-26 22:08 UTC
